services:
  mysql:
    image: mysql:8.0
    container_name: agorium-db-prod
    restart: always
    env_file:
      - .env      # Chargement du fichier d'environnement principal
      - .env.prod # Chargement du fichier d'environnement spécifique à pre-prod
    environment:
      MYSQL_ROOT_PASSWORD: caS>13200.ago
      MYSQL_DATABASE: agorium_db_prod
      MYSQL_USER: admin
      MYSQL_PASSWORD: caS*gg<5050.
    volumes:
      - mysql-data-prod:/var/lib/mysql
    networks:
      - proxy

  backend:
    build: ./backend
    container_name: agorium-backend-prod
    depends_on:
      - mysql
    env_file:
      - .env          # Chargement du fichier d'environnement principal
      - .env.prod # Chargement du fichier d'environnement spécifique à pre-prod
    environment:
      - NODE_ENV=production  # Définition spécifique à cet environnement
    networks:
      - proxy
    volumes:
      - ./backend:/app
      - /home/gamma/agorium-prod-uploads:/app/public/uploads
    command: >
      sh -c "
        npm install &&
        dockerize -wait tcp://agorium-db-prod:3306 -timeout 60s &&
        npx sequelize-cli db:migrate &&
        node ./bin/www"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_APP_MODE: production
    container_name: agorium-frontend-prod
    depends_on:
      - backend
    env_file:
      - .env      # Chargement du fichier d'environnement principal
      - .env.prod # Chargement du fichier d'environnement spécifique à pre-prod
    networks:
      - proxy

volumes:
  mysql-data-prod:

networks:
  proxy:
    external: true
