services:
  redis:
    image: redis:7-alpine
    container_name: agorium-redis-prod
    restart: always
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis-data-prod:/data
    networks:
      - proxy

  mysql:
    image: mysql:8.0
    container_name: agorium-db-prod
    restart: always
    env_file:
      - .env
      - .env.prod
    environment:
      MYSQL_ROOT_PASSWORD: caS>13200.ago
      MYSQL_DATABASE: agorium_db_prod
      MYSQL_USER: admin
      MYSQL_PASSWORD: caS*gg<5050.
    volumes:
      - mysql-data-prod:/var/lib/mysql
    networks:
      - proxy

  backend:
    build: ./backend
    container_name: agorium-backend-prod
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
      - .env.prod
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - proxy
    volumes:
      - ./backend:/app
      - /home/gamma/agorium-prod-uploads:/app/public/uploads
    command: >
      sh -c "
        npm install &&
        dockerize -wait tcp://agorium-db-prod:3306 -wait tcp://redis:6379 -timeout 60s &&
        npx sequelize-cli db:migrate &&
        node ./bin/www"

  worker:
    build: ./backend
    container_name: agorium-worker-prod
    restart: always
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
      - .env.prod
    environment:
      - NODE_ENV=production
      - REDIS_HOST=agorium-redis-prod
      - REDIS_PORT=6379
    volumes:
      - ./backend:/app
      - /home/gamma/agorium-prod-uploads:/app/public/uploads
    command: node ./workers/videoWorker.js
    networks:
      - proxy

  frontend:
    build:
      context: ./frontend
      args:
        VITE_APP_MODE: production
    container_name: agorium-frontend-prod
    depends_on:
      - backend
    env_file:
      - .env
      - .env.prod
    networks:
      - proxy

volumes:
  mysql-data-prod:
  redis-data-prod:

networks:
  proxy:
    external: true
