services:
  mysql:
    image: mysql:8.0
    container_name: agorium-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gg5050
      MYSQL_DATABASE: agorium_db_dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: azerty
    env_file:
      - .env
      - .env.dev
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    container_name: agorium-backend
    depends_on:
      - mysql
    env_file:
      - .env
      - .env.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    # add this to sh for seed: node seeds/all.js &&
    command: >
      sh -c "
        dockerize -wait tcp://agorium-db:3306 -timeout 120s &&
        npx sequelize-cli db:migrate &&
        node ./bin/www"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_APP_MODE: development
    container_name: agorium-frontend
    depends_on:
      - backend
    env_file:
      - .env
      - .env.dev
    ports:
      - "8080:80"

volumes:
  mysql-data:
